elec_data <- read.table("./data/household_power_consumption.txt", sep = ";", header = TRUE)
elec_data <- elec_data[which(as.character(elec_data$Date) == "1/2/2007" | as.character(elec_data$Date) == "2/2/2007"), ]
elec_data <- transform(elec_data, datetime = paste(Date, Time, sep = " "))
elec_data <- transform(elec_data, Global_active_power = as.numeric(as.character(Global_active_power)))
elec_data <- transform(elec_data, datetime = strptime(datetime, format = "%d/%m/%Y %H:%M:%S"))
elec_data <- transform(elec_data, Voltage = as.numeric(as.character(Voltage)), Global_reactive_power = as.numeric(as.character(Global_reactive_power)))
par(mfrow = c(2,2), mar = c(4,4,2,1))
with(elec_data, plot(datetime, Global_active_power, type = "l", ylab = "Global active power (kilowatts)"))
with(elec_data, plot(datetime, Voltage, type = "l"))
with(elec_data, plot(datetime, Sub_metering_1, ylab = "Energy sub metering", type = "n"))
with(elec_data, lines(datetime, Sub_metering_1, col = "black"))
with(elec_data, lines(datetime, Sub_metering_2, col = "red"))
with(elec_data, lines(datetime, Sub_metering_3, col = "blue"))
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = c(1,1,1), col = c("black","red","blue"))
with(elec_data, plot(datetime, Global_reactive_power, type = "l"))
dev.copy(png, "plot4.png")
dev.off()